[CORE-17] Update go version and toolchain version to 1.21.1 to resolve vulnerability
Context: https://github.com/dydxprotocol/cosmos-sdk/actions/runs/6126061229/job/16629299626?pr=26

Details:

Scanning your code and 822 packages across 139 dependent modules for known vulnerabilities...
Vulnerability #1: GO-2023-2043
    Improper handling of special tags within script contexts in html/template
  More info: https://pkg.go.dev/vuln/GO-2023-2043
  Standard library
    Found in: html/template@go1.19.13
    Fixed in: html/template@go1.21.1
    Example traces found:
Error:       #1: server/api/server.go:111:27: api.Server.Start calls server.Serve, which eventually calls template.Template.Execute
Error:       #2: server/api/server.go:111:27: api.Server.Start calls server.Serve, which eventually calls template.Template.ExecuteTemplate
Vulnerability #2: GO-2023-2041
    Improper handling of HTML-like comments in script contexts in html/template
  More info: https://pkg.go.dev/vuln/GO-2023-2041
  Standard library
    Found in: html/template@go1.19.13
    Fixed in: html/template@go1.21.1
    Example traces found:
Error:       #1: server/api/server.go:111:27: api.Server.Start calls server.Serve, which eventually calls template.Template.Execute
Error:       #2: server/api/server.go:111:27: api.Server.Start calls server.Serve, which eventually calls template.Template.ExecuteTemplate
=== Informational ===
Found 2 vulnerabilities in packages that you import, but there are no call
stacks leading to the use of these vulnerabilities. You may not need to
take any action. See https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
for details.
Vulnerability #1: GO-2023-2045
    Memory exhaustion in QUIC connection handling in crypto/tls
  More info: https://pkg.go.dev/vuln/GO-2023-2045
  Standard library
    Found in: crypto/tls@go1.19.13
    Fixed in: crypto/tls@go1.21.1
Vulnerability #2: GO-2023-2044
    Panic when processing post-handshake message on QUIC connections in
    crypto/tls
  More info: https://pkg.go.dev/vuln/GO-2023-2044
  Standard library
    Found in: crypto/tls@go1.19.13
    Fixed in: crypto/tls@go1.21.1
Your code is affected by 2 vulnerabilities from the Go standard library.
Share feedback at https://go.dev/s/govulncheck-feedback.